// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  简单问候命令，用于演示。 */
	greet: (name: string) => typedError<string, AppError>(__TAURI_INVOKE("greet", { name })),
	/**
	 *  从磁盘加载用户偏好设置。
	 *  若文件不存在则返回默认偏好。
	 */
	loadPreferences: () => typedError<AppPreferences, AppError>(__TAURI_INVOKE("load_preferences")),
	/**
	 *  保存用户偏好设置到磁盘。
	 *  使用原子写入（临时文件 + 重命名）以防止数据损坏。
	 */
	savePreferences: (preferences: AppPreferences) => typedError<null, AppError>(__TAURI_INVOKE("save_preferences", { preferences })),
	/**
	 *  发送原生系统通知。
	 *  在移动平台上会返回错误，因为暂不支持通知。
	 */
	sendNativeNotification: (title: string, body: string | null) => typedError<null, AppError>(__TAURI_INVOKE("send_native_notification", { title, body })),
	/**
	 *  将紧急数据保存到 JSON 文件以供后续恢复。
	 *  校验文件名并强制限制 10MB 大小。
	 * 
	 *  接受 JSON 字符串（而非已解析的值），以避免 tauri-specta 的 TypeScript
	 *  代码生成中出现递归类型栈溢出。
	 */
	saveEmergencyData: (filename: string, data: string) => typedError<null, RecoveryError>(__TAURI_INVOKE("save_emergency_data", { filename, data })),
	/**
	 *  从先前保存的 JSON 文件加载紧急数据。
	 *  若文件不存在则返回 FileNotFound。
	 * 
	 *  返回 JSON 字符串（而非已解析的值），以避免 tauri-specta 的 TypeScript
	 *  代码生成中出现递归类型栈溢出。
	 */
	loadEmergencyData: (filename: string) => typedError<string, RecoveryError>(__TAURI_INVOKE("load_emergency_data", { filename })),
	/**
	 *  删除超过 7 天的恢复文件。
	 *  返回被删除的文件数。
	 */
	cleanupOldRecoveryFiles: () => typedError<number, RecoveryError>(__TAURI_INVOKE("cleanup_old_recovery_files")),
	/**
	 *  显示快速面板窗口并使其成为 key window（用于接收键盘输入）。
	 * 
	 *  执行步骤：
	 *  1. 调用 `position_quick_pane_on_cursor_monitor` 重新定位到光标所在显示器；
	 *  2. macOS：调用 `panel.show_and_make_key()` 显示并获取键盘焦点；
	 *  3. 其他平台：调用 `window.show()` + `window.set_focus()` 模拟。
	 * 
	 *  # 错误
	 * 
	 *  - 若面板未初始化（[`init_quick_pane`] 未调用），返回 [`AppError::not_found`]；
	 *  - 若显示或聚焦失败，返回 [`AppError::window`]。
	 * 
	 *  # 前端触发方式
	 * 
	 *  作为 Tauri 命令暴露给前端，前端通过 `invoke('show_quick_pane')` 调用。
	 *  也可由 [`register_quick_pane_shortcut`] 注册的全局快捷键间接触发。
	 * 
	 *  [`init_quick_pane`]: init_quick_pane
	 *  [`register_quick_pane_shortcut`]: register_quick_pane_shortcut
	 */
	showQuickPane: () => typedError<null, AppError>(__TAURI_INVOKE("show_quick_pane")),
	/**
	 *  关闭快速面板窗口。
	 * 
	 *  在 macOS 上，隐藏前先调用 `resign_key_window()` 取消 key window 状态，
	 *  以避免 macOS 自动激活主窗口（这会导致切换 Space 的视觉干扰）。
	 * 
	 *  # 幂等性
	 * 
	 *  若面板已隐藏，直接返回 `Ok(())`，避免重复触发隐藏逻辑。
	 *  这对于 `resign_key_window` 触发的 blur 事件 → 再次调用 dismiss 的
	 *  循环场景至关重要。
	 * 
	 *  # 错误
	 * 
	 *  - 非 macOS 平台：若 `window.hide()` 失败，返回 [`AppError::window`]；
	 *  - macOS 平台：若面板查找失败，静默返回 `Ok(())`（面板可能未初始化）。
	 * 
	 *  # 前端触发方式
	 * 
	 *  作为 Tauri 命令暴露给前端，前端在以下场景调用：
	 *  - 用户按 Esc 键；
	 *  - 面板失焦（blur 事件）；
	 *  - 提交输入后自动隐藏。
	 */
	dismissQuickPane: () => typedError<null, AppError>(__TAURI_INVOKE("dismiss_quick_pane")),
	/**
	 *  切换快速面板窗口的可见性。
	 * 
	 *  通过 `is_quick_pane_visible` 检查当前状态，决定调用
	 *  [`dismiss_quick_pane`] 还是 [`show_quick_pane`]。
	 * 
	 *  这是全局快捷键绑定的默认动作：按下快捷键时，若面板已显示则隐藏，
	 *  若已隐藏则显示。
	 * 
	 *  # 前端触发方式
	 * 
	 *  作为 Tauri 命令暴露给前端，但通常由 [`register_quick_pane_shortcut`]
	 *  注册的全局快捷键直接调用。
	 */
	toggleQuickPane: () => typedError<null, AppError>(__TAURI_INVOKE("toggle_quick_pane")),
	/**
	 *  返回默认快捷键常量，供前端使用。
	 * 
	 *  前端在偏好设置界面需要显示默认值作为占位符或"重置为默认"按钮的值。
	 *  通过 Tauri 命令暴露（而非在前端硬编码），保证 Rust 与前端
	 *  默认值始终一致。
	 * 
	 *  # 返回值
	 * 
	 *  返回 [`crate::types::DEFAULT_QUICK_PANE_SHORTCUT`] 的字符串副本。
	 */
	getDefaultQuickPaneShortcut: () => __TAURI_INVOKE<string>("get_default_quick_pane_shortcut"),
	/**
	 *  更新快速面板的全局快捷键。
	 * 
	 *  传入 `None` 则重置为默认值（[`DEFAULT_QUICK_PANE_SHORTCUT`]）。
	 * 
	 *  # 执行步骤
	 * 
	 *  1. 校验输入：非空且长度不超过 50 字符；
	 *  2. 桌面平台：调用 [`register_quick_pane_shortcut`] 注册新快捷键
	 *     （内部会先注销旧快捷键）；
	 *  3. 非桌面平台：记录警告并返回 `Ok(())`。
	 * 
	 *  # 参数
	 * 
	 *  - `app`：Tauri 应用句柄；
	 *  - `shortcut`：新的快捷键字符串（如 `"CommandOrControl+Shift+Space"`），
	 *    或 `None` 重置为默认值。
	 * 
	 *  # 错误
	 * 
	 *  - 若快捷键为空字符串，返回 [`AppError::validation`]；
	 *  - 若快捷键长度超过 50 字符，返回 [`AppError::validation`]；
	 *  - 若 [`register_quick_pane_shortcut`] 失败，传播其错误。
	 * 
	 *  # 前端触发方式
	 * 
	 *  作为 Tauri 命令暴露给前端，前端在偏好设置面板中用户修改快捷键后调用。
	 *  调用成功后，前端还应通过 `save_preferences` 持久化新快捷键到
	 *  `preferences.json`，以便下次启动时通过 [`load_quick_pane_shortcut`]
	 *  恢复。
	 * 
	 *  [`DEFAULT_QUICK_PANE_SHORTCUT`]: crate::types::DEFAULT_QUICK_PANE_SHORTCUT
	 *  [`register_quick_pane_shortcut`]: register_quick_pane_shortcut
	 *  [`load_quick_pane_shortcut`]: crate::commands::preferences::load_quick_pane_shortcut
	 */
	updateQuickPaneShortcut: (shortcut: string | null) => typedError<null, AppError>(__TAURI_INVOKE("update_quick_pane_shortcut", { shortcut })),
	/**
	 *  更新托盘图标状态（正常 / 通知徽标）。
	 * 
	 *  作为 Tauri 命令暴露给前端，前端可在收到通知或未读数变化时
	 *  触发徽标显示。
	 */
	setTrayIconState: (state: TrayIconState) => typedError<null, AppError>(__TAURI_INVOKE("set_tray_icon_state", { state })),
	/**
	 *  将窗口移动到相对于托盘图标的位置（如弹出式面板）。
	 * 
	 *  作为 Tauri 命令暴露给前端，前端可将快速面板或弹出窗口
	 *  定位到托盘图标附近。
	 */
	moveWindowToTray: (windowLabel: string, position: TrayPosition) => typedError<null, AppError>(__TAURI_INVOKE("move_window_to_tray", { windowLabel, position })),
	/**
	 *  读取崩溃报告文件（若存在）。
	 *  若未找到崩溃文件则返回 None。
	 */
	readCrashReport: () => typedError<{
	/**  崩溃类型标识（当前固定为 `"rust_panic"`） */
	crash_type: string,
	/**  panic 消息文本（已脱敏） */
	message: string,
	/**  源码位置（`文件:行号:列号`），可能为 `None` */
	location: string | null,
	/**  完整的调用栈回溯字符串（已脱敏） */
	backtrace: string,
	/**  Unix 时间戳（自 epoch 起的秒数，浮点数） */
	timestamp: number | null,
	/**  崩溃发生时的应用版本号 */
	app_version: string,
} | null, AppError>(__TAURI_INVOKE("read_crash_report")),
	/**
	 *  删除崩溃报告文件。
	 *  在崩溃已发送到 Sentry 或被用户忽略后调用。
	 */
	deleteCrashReport: () => typedError<null, AppError>(__TAURI_INVOKE("delete_crash_report")),
	/**
	 *  设置崩溃报告授权状态。
	 * 
	 *  由前端在用户通过偏好设置面板或崩溃报告对话框授予或拒绝授权时调用。
	 *  状态既保存在内存中（通过 `CONSENT_STATE`），**也**持久化到 Rust 端的
	 *  `preferences.json`，因此即使前端未调用 `save_preferences`，
	 *  重启后该状态也会保留。
	 */
	setConsent: (consent: boolean | null) => typedError<null, AppError>(__TAURI_INVOKE("set_consent", { consent })),
	/**
	 *  创建新线程。
	 * 
	 *  调用 codex-rs 的 `thread/start` 方法，使用指定的模型和工作目录
	 *  初始化一个新的会话线程。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 线程启动参数（模型、工作目录等）
	 * 
	 *  # 返回
	 * 
	 *  返回 `thread/start` 的 JSON 字符串，包含 `thread`、`model`、
	 *  `cwd` 等字段。前端 `JSON.parse()` 后通过 TypeScript 类型断言使用。
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::NotInitialized`] — codex 运行时未初始化
	 *  - [`AppError::TypedRequestError`] — 请求失败（传输/服务器/反序列化）
	 *  - [`AppError::Serialization`] — 响应序列化为 JSON 字符串失败
	 */
	threadStart: (args: ThreadStartArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("thread_start", { args })),
	/**
	 *  列出所有线程。
	 * 
	 *  调用 codex-rs 的 `thread/list` 方法，分页返回线程列表。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 分页参数（游标、每页数量）
	 * 
	 *  # 返回
	 * 
	 *  返回 `thread/list` 的 JSON 字符串，包含 `threads` 数组和
	 *  `nextCursor` 分页游标。
	 */
	threadList: (args: ThreadListArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("thread_list", { args })),
	/**
	 *  读取线程详情。
	 * 
	 *  调用 codex-rs 的 `thread/read` 方法，获取线程信息和可选的 turn 历史。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `thread_id` 和 `include_turns` 标志
	 * 
	 *  # 返回
	 * 
	 *  返回 `thread/read` 的 JSON 字符串，包含 `thread` 对象。
	 */
	threadRead: (args: ThreadReadArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_read", { args })),
	/**
	 *  取消订阅线程。
	 * 
	 *  调用 codex-rs 的 `thread/unsubscribe` 方法，停止接收指定线程的事件。
	 *  这是在关闭线程前释放服务器端资源的推荐操作。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含要取消订阅的 `thread_id`
	 * 
	 *  # 返回
	 * 
	 *  返回 `thread/unsubscribe` 的 JSON 字符串，包含 `status` 字段
	 * （值为 `"notLoaded"`、`"notSubscribed"` 或 `"unsubscribed"`）。
	 */
	threadUnsubscribe: (args: ThreadUnsubscribeArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_unsubscribe", { args })),
	/**
	 *  恢复线程（`thread/resume`）。
	 * 
	 *  加载已有线程到内存，可覆盖模型、工作目录等配置。
	 *  复杂字段（history/sandbox/approvalPolicy 等）通过 `params_json` 透传。
	 */
	threadResume: (args: ThreadResumeArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("thread_resume", { args })),
	/**
	 *  分叉线程（`thread/fork`）。
	 * 
	 *  从指定 turn 创建线程副本，可覆盖模型、工作目录等配置。
	 */
	threadFork: (args: ThreadForkArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("thread_fork", { args })),
	/**
	 *  归档线程（`thread/archive`）。
	 * 
	 *  将线程标记为已归档，归档后的线程默认不出现在线程列表中。
	 */
	threadArchive: (args: ThreadArchiveArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_archive", { args })),
	/**
	 *  取消归档线程（`thread/unarchive`）。
	 * 
	 *  将线程从归档状态恢复到正常状态。
	 */
	threadUnarchive: (args: ThreadUnarchiveArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_unarchive", { args })),
	/**
	 *  删除线程（`thread/delete`）。
	 * 
	 *  永久删除线程及其关联的 rollout 文件。此操作不可逆。
	 */
	threadDelete: (args: ThreadDeleteArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_delete", { args })),
	/**
	 *  回滚线程（`thread/rollback`，已废弃）。
	 * 
	 *  从线程末尾移除指定数量的 turn。仅修改历史记录，不回滚文件变更。
	 * 
	 *  # 废弃说明
	 *  协议层标记为 DEPRECATED，未来版本可能移除。
	 */
	threadRollback: (args: ThreadRollbackArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_rollback", { args })),
	/**  重命名线程（`thread/name/set`）。 */
	threadSetName: (args: ThreadSetNameArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_set_name", { args })),
	/**
	 *  更新线程元数据（`thread/metadata/update`）。
	 * 
	 *  目前支持更新 Git 信息（sha/branch/originUrl）。
	 *  每个字段可省略（保持不变）、设为 null（清除）或设为字符串（替换）。
	 */
	threadMetadataUpdate: (args: ThreadMetadataUpdateArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("thread_metadata_update", { args })),
	/**
	 *  设置线程目标（`thread/goal/set`）。
	 * 
	 *  可设置目标描述、状态和 token 预算。所有字段可选，null 表示清除。
	 */
	threadGoalSet: (args: ThreadGoalSetArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("thread_goal_set", { args })),
	/**  获取线程目标（`thread/goal/get`）。 */
	threadGoalGet: (args: ThreadGoalGetArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_goal_get", { args })),
	/**  清除线程目标（`thread/goal/clear`）。 */
	threadGoalClear: (args: ThreadGoalClearArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_goal_clear", { args })),
	/**
	 *  列出已加载到内存的线程（`thread/loaded/list`）。
	 * 
	 *  返回当前服务器进程中活跃的线程 ID 列表。
	 */
	threadLoadedList: (args: ThreadLoadedListArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("thread_loaded_list", { args })),
	/**
	 *  搜索线程（`thread/search`，experimental）。
	 * 
	 *  按关键词搜索线程标题和内容，支持过滤和排序。
	 */
	threadSearch: (args: ThreadSearchArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("thread_search", { args })),
	/**
	 *  列出线程的 turn（`thread/turns/list`，experimental）。
	 * 
	 *  分页返回线程的 turn 历史，可选择 item 详情级别。
	 */
	threadTurnsList: (args: ThreadTurnsListArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("thread_turns_list", { args })),
	/**
	 *  列出线程的消息项（`thread/items/list`，experimental）。
	 * 
	 *  **核心命令**：分页拉取线程内的 ThreadItem，替代前端 mock 数据。
	 *  可按 turn_id 过滤，支持游标分页和排序方向。
	 */
	threadItemsList: (args: ThreadItemsListArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("thread_items_list", { args })),
	/**
	 *  注入原始 Responses API items（`thread/inject_items`）。
	 * 
	 *  向线程追加原始 items，不触发新 turn。用于客户端预填充上下文。
	 */
	threadInjectItems: (args: ThreadInjectItemsArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_inject_items", { args })),
	/**
	 *  启动线程压缩（`thread/compact/start`）。
	 * 
	 *  触发线程历史的上下文压缩，将旧 turn 总结为更紧凑的形式。
	 */
	threadCompactStart: (args: ThreadCompactStartArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_compact_start", { args })),
	/**
	 *  执行 shell 命令（`thread/shellCommand`）。
	 * 
	 *  在线程的工作目录中执行 shell 命令。命令在线程沙箱外运行，
	 *  保留 shell 语法（管道、重定向等）。
	 */
	threadShellCommand: (args: ThreadShellCommandArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_shell_command", { args })),
	/**
	 *  批准 Guardian 拒绝的操作（`thread/approveGuardianDeniedAction`）。
	 * 
	 *  允许用户覆盖 Guardian 的安全决策，强制执行被拒绝的操作。
	 */
	threadApproveGuardianDeniedAction: (args: ThreadApproveGuardianDeniedActionArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_approve_guardian_denied_action", { args })),
	/**
	 *  增加线程 elicitation 计数（`thread/increment_elicitation`，experimental）。
	 * 
	 *  用于外部助手在用户审批等待期间暂停超时计时。
	 */
	threadIncrementElicitation: (args: ThreadIncrementElicitationArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_increment_elicitation", { args })),
	/**
	 *  减少线程 elicitation 计数（`thread/decrement_elicitation`，experimental）。
	 * 
	 *  计数归零时恢复超时计时。
	 */
	threadDecrementElicitation: (args: ThreadDecrementElicitationArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_decrement_elicitation", { args })),
	/**
	 *  更新线程设置（`thread/settings/update`，experimental）。
	 * 
	 *  协议层 ThreadSettingsUpdateParams 有 13 个字段（含 AskForApproval/SandboxPolicy 等），
	 *  通过 `params_json` 承载完整协议参数。
	 */
	threadSettingsUpdate: (args: ThreadSettingsUpdateArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_settings_update", { args })),
	/**
	 *  设置线程记忆模式（`thread/memoryMode/set`，experimental）。
	 * 
	 *  启用或禁用线程的长期记忆功能。
	 */
	threadMemoryModeSet: (args: ThreadMemoryModeSetArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_memory_mode_set", { args })),
	/**
	 *  清理线程的后台终端（`thread/backgroundTerminals/clean`，experimental）。
	 * 
	 *  清除已终止的后台终端进程记录。
	 */
	threadBackgroundTerminalsClean: (args: ThreadBackgroundTerminalsCleanArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_background_terminals_clean", { args })),
	/**
	 *  列出线程的后台终端（`thread/backgroundTerminals/list`，experimental）。
	 * 
	 *  分页返回线程关联的后台终端进程列表。
	 */
	threadBackgroundTerminalsList: (args: ThreadBackgroundTerminalsListArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("thread_background_terminals_list", { args })),
	/**
	 *  终止线程的后台终端（`thread/backgroundTerminals/terminate`，experimental）。
	 * 
	 *  终止指定 process_id 的后台终端进程。
	 */
	threadBackgroundTerminalsTerminate: (args: ThreadBackgroundTerminalsTerminateArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_background_terminals_terminate", { args })),
	/**
	 *  启动线程实时会话（`thread/realtime/start`，experimental）。
	 * 
	 *  协议层 ThreadRealtimeStartParams 有 13 个字段（含 RealtimeOutputModality 等），
	 *  通过 `params_json` 承载完整协议参数。
	 */
	threadRealtimeStart: (args: ThreadRealtimeStartArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_realtime_start", { args })),
	/**
	 *  追加实时音频输入（`thread/realtime/appendAudio`，experimental）。
	 * 
	 *  向线程实时会话追加音频块。audio_json 格式：
	 *  `{ "data": "<base64>", "sampleRate": 24000, "numChannels": 1, ... }`。
	 */
	threadRealtimeAppendAudio: (args: ThreadRealtimeAppendAudioArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_realtime_append_audio", { args })),
	/**
	 *  追加实时文本输入（`thread/realtime/appendText`，experimental）。
	 * 
	 *  向线程实时会话追加文本，可指定角色（user/developer/assistant）。
	 */
	threadRealtimeAppendText: (args: ThreadRealtimeAppendTextArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("thread_realtime_append_text", { args })),
	/**
	 *  追加实时语音输入（`thread/realtime/appendSpeech`，experimental）。
	 * 
	 *  向线程实时会话追加可合成语音的文本。
	 */
	threadRealtimeAppendSpeech: (args: ThreadRealtimeAppendSpeechArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_realtime_append_speech", { args })),
	/**  停止线程实时会话（`thread/realtime/stop`，experimental）。 */
	threadRealtimeStop: (args: ThreadRealtimeStopArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_realtime_stop", { args })),
	/**
	 *  列出实时会话支持的语音（`thread/realtime/listVoices`，experimental）。
	 * 
	 *  协议层为空参数，DTO 也为空结构体。
	 */
	threadRealtimeListVoices: (args: ThreadRealtimeListVoicesArgs) => typedError<string, AppError>(__TAURI_INVOKE("thread_realtime_list_voices", { args })),
	/**
	 *  启动新的会话轮次。
	 * 
	 *  调用 codex-rs 的 `turn/start` 方法，在指定线程上开始一轮新的对话。
	 *  前端通过 `input` 传入用户消息（文本、图片等）。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 轮次启动参数（线程 ID、输入、模型、工作目录）
	 * 
	 *  # 返回
	 * 
	 *  返回 `turn/start` 的 JSON 字符串，包含 `turn` 对象。
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `thread_id` 为空
	 *  - [`AppError::NotInitialized`] — codex 运行时未初始化
	 *  - [`AppError::TypedRequestError`] — 请求失败
	 */
	turnStart: (args: TurnStartArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("turn_start", { args })),
	/**
	 *  在当前轮次中追加用户输入（转向）。
	 * 
	 *  调用 codex-rs 的 `turn/steer` 方法，在正在进行的轮次中注入新的
	 *  用户输入。`expected_turn_id` 必须与当前活跃的 turn ID 匹配。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 转向参数（线程 ID、输入、预期 turn ID）
	 * 
	 *  # 返回
	 * 
	 *  返回 `turn/steer` 的 JSON 字符串，包含 `turnId` 字段。
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `thread_id` 或 `expected_turn_id` 为空
	 */
	turnSteer: (args: TurnSteerArgs) => typedError<string, AppError>(__TAURI_INVOKE("turn_steer", { args })),
	/**
	 *  中断指定线程的当前轮次。
	 * 
	 *  调用 codex-rs 的 `turn/interrupt` 方法，停止正在进行的轮次。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 中断参数（线程 ID、轮次 ID）
	 * 
	 *  # 返回
	 * 
	 *  返回 `turn/interrupt` 的 JSON 字符串。
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `thread_id` 或 `turn_id` 为空
	 */
	turnInterrupt: (args: TurnInterruptArgs) => typedError<string, AppError>(__TAURI_INVOKE("turn_interrupt", { args })),
	/**
	 *  读取文件内容。
	 * 
	 *  调用 codex-rs 的 `fs/readFile` 方法，返回 base64 编码的文件内容。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `path`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `path` 为空
	 */
	fsReadFile: (args: FsReadFileArgs) => typedError<string, AppError>(__TAURI_INVOKE("fs_read_file", { args })),
	/**
	 *  写入文件内容。
	 * 
	 *  调用 codex-rs 的 `fs/writeFile` 方法，将 base64 编码的数据写入指定路径。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `path` 和 `dataBase64`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `path` 为空
	 */
	fsWriteFile: (args: FsWriteFileArgs) => typedError<string, AppError>(__TAURI_INVOKE("fs_write_file", { args })),
	/**
	 *  创建目录。
	 * 
	 *  调用 codex-rs 的 `fs/createDirectory` 方法，可选是否递归创建父目录。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `path` 和可选的 `recursive`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `path` 为空
	 */
	fsCreateDirectory: (args: FsCreateDirectoryArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("fs_create_directory", { args })),
	/**
	 *  获取文件或目录的元数据。
	 * 
	 *  调用 codex-rs 的 `fs/getMetadata` 方法，返回是否为目录/文件/符号链接
	 *  以及创建和修改时间。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `path`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `path` 为空
	 */
	fsGetMetadata: (args: FsGetMetadataArgs) => typedError<string, AppError>(__TAURI_INVOKE("fs_get_metadata", { args })),
	/**
	 *  列出目录内容。
	 * 
	 *  调用 codex-rs 的 `fs/readDirectory` 方法，返回直接子条目列表。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `path`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `path` 为空
	 */
	fsReadDirectory: (args: FsReadDirectoryArgs) => typedError<string, AppError>(__TAURI_INVOKE("fs_read_directory", { args })),
	/**
	 *  删除文件或目录。
	 * 
	 *  调用 codex-rs 的 `fs/remove` 方法，可选是否递归删除和强制删除。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `path` 和可选的 `recursive`、`force`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `path` 为空
	 */
	fsRemove: (args: FsRemoveArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("fs_remove", { args })),
	/**
	 *  复制文件或目录。
	 * 
	 *  调用 codex-rs 的 `fs/copy` 方法，复制目录时需要设置 `recursive`。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `sourcePath`、`destinationPath` 和可选的 `recursive`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `sourcePath` 或 `destinationPath` 为空
	 */
	fsCopy: (args: FsCopyArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("fs_copy", { args })),
	/**
	 *  开始监听文件系统变更。
	 * 
	 *  调用 codex-rs 的 `fs/watch` 方法，注册一个文件或目录的监听器。
	 *  后续变更通过 `fs/changed` 通知推送。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `watchId` 和 `path`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `watchId` 或 `path` 为空
	 */
	fsWatch: (args: FsWatchArgs) => typedError<string, AppError>(__TAURI_INVOKE("fs_watch", { args })),
	/**
	 *  停止监听文件系统变更。
	 * 
	 *  调用 codex-rs 的 `fs/unwatch` 方法，取消之前通过 `fs/watch` 注册的监听器。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `watchId`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `watchId` 为空
	 */
	fsUnwatch: (args: FsUnwatchArgs) => typedError<string, AppError>(__TAURI_INVOKE("fs_unwatch", { args })),
	/**
	 *  启动 MCP 服务器的 OAuth 登录。
	 * 
	 *  调用 codex-rs 的 `mcpServer/oauth/login` 方法，返回授权 URL
	 *  供前端在浏览器中打开。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `name` 和可选的 `threadId`、`scopes`、`timeoutSecs`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `name` 为空
	 */
	mcpServerOauthLogin: (args: McpServerOauthLoginArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("mcp_server_oauth_login", { args })),
	/**
	 *  列出 MCP 服务器状态。
	 * 
	 *  调用 codex-rs 的 `mcpServerStatus/list` 方法，分页返回所有 MCP
	 *  服务器的状态、工具和资源信息。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 分页参数（游标、每页数量、线程 ID）
	 */
	mcpServerStatusList: (args: McpServerStatusListArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("mcp_server_status_list", { args })),
	/**
	 *  读取 MCP 资源内容。
	 * 
	 *  调用 codex-rs 的 `mcpServer/resource/read` 方法，获取指定 MCP 服务器
	 *  上特定 URI 的资源内容。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `server`、`uri` 和可选的 `threadId`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `server` 或 `uri` 为空
	 */
	mcpResourceRead: (args: McpResourceReadArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("mcp_resource_read", { args })),
	/**
	 *  调用 MCP 服务器工具。
	 * 
	 *  调用 codex-rs 的 `mcpServer/tool/call` 方法，在指定线程上执行
	 *  MCP 服务器提供的工具。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `threadId`、`server`、`tool` 和可选的 `arguments`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `threadId`、`server` 或 `tool` 为空
	 */
	mcpServerToolCall: (args: McpServerToolCallArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("mcp_server_tool_call", { args })),
	/**
	 *  刷新 MCP 服务器配置。
	 * 
	 *  调用 codex-rs 的 `config/mcpServer/reload` 方法，重新加载所有
	 *  已注册的 MCP 服务器配置。
	 * 
	 *  # 参数
	 * 
	 *  - `_args` — 无参数（空结构体）
	 */
	mcpServerRefresh: (args: McpServerRefreshArgs) => typedError<string, AppError>(__TAURI_INVOKE("mcp_server_refresh", { args })),
	/**
	 *  读取配置。
	 * 
	 *  调用 codex-rs 的 `config/read` 方法，返回当前生效的配置和来源信息。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含可选的 `includeLayers` 和 `cwd`
	 */
	configRead: (args: ConfigReadArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("config_read", { args })),
	/**
	 *  写入单个配置项。
	 * 
	 *  调用 codex-rs 的 `config/value/write` 方法，将指定键路径的值写入
	 *  配置文件。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `keyPath`、`value`、`mergeStrategy` 和可选的 `filePath`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `keyPath` 为空或 `mergeStrategy` 无效
	 */
	configValueWrite: (args: ConfigValueWriteArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("config_value_write", { args })),
	/**
	 *  批量写入配置项。
	 * 
	 *  调用 codex-rs 的 `config/batchWrite` 方法，一次性写入多个配置编辑。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `edits`（JSON 数组）和可选的 `filePath`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `edits` 不是数组
	 */
	configBatchWrite: (args: ConfigBatchWriteArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("config_batch_write", { args })),
	/**
	 *  启动账户登录流程。
	 * 
	 *  调用 codex-rs 的 `account/login/start` 方法，根据登录类型启动
	 *  不同的认证流程。`LoginAccountParams` 是一个 tagged union，
	 *  我们根据 `login_type` 构造对应的 JSON 结构。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `loginType` 和可选的 `apiKey`
	 * 
	 *  # 返回
	 * 
	 *  - `apiKey` 类型：返回空响应
	 *  - `chatgpt` 类型：返回 `loginId` 和 `authUrl`
	 *  - `chatgptDeviceCode` 类型：返回 `loginId`、`verificationUrl` 和 `userCode`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `loginType` 无效或 `apiKey` 缺失
	 */
	loginAccount: (args: LoginAccountArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("login_account", { args })),
	/**
	 *  取消正在进行的登录流程。
	 * 
	 *  调用 codex-rs 的 `account/login/cancel` 方法，取消之前通过
	 *  `login_account` 启动的登录会话。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `loginId`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `loginId` 为空
	 */
	cancelLoginAccount: (args: CancelLoginAccountArgs) => typedError<string, AppError>(__TAURI_INVOKE("cancel_login_account", { args })),
	/**
	 *  登出当前账户。
	 * 
	 *  调用 codex-rs 的 `account/logout` 方法，清除当前会话的认证状态。
	 * 
	 *  # 参数
	 * 
	 *  - `_args` — 无参数（空结构体）
	 */
	logoutAccount: (args: LogoutAccountArgs) => typedError<string, AppError>(__TAURI_INVOKE("logout_account", { args })),
	/**
	 *  获取当前账户信息。
	 * 
	 *  调用 codex-rs 的 `account/read` 方法，返回当前登录的账户状态
	 *  和是否需要 OpenAI 认证。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含可选的 `refreshToken`
	 */
	getAccount: (args: GetAccountArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("get_account", { args })),
	/**
	 *  执行一次性命令。
	 * 
	 *  调用 codex-rs 的 `command/exec` 方法，在服务器沙箱内执行一个
	 *  独立的命令。支持 PTY 模式和 stdin/stdout 流式传输。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 命令参数（argv 向量、进程 ID、模式标志等）
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `command` 为空数组
	 */
	commandExec: (args: CommandExecArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("command_exec", { args })),
	/**
	 *  写入 stdin 或关闭 stdin。
	 * 
	 *  调用 codex-rs 的 `command/exec/write` 方法，向正在运行的
	 *  `command/exec` 会话写入 base64 编码的 stdin 数据，或关闭 stdin。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `processId` 和可选的 `deltaBase64`、`closeStdin`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `processId` 为空
	 */
	commandExecWrite: (args: CommandExecWriteArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("command_exec_write", { args })),
	/**
	 *  终止正在运行的命令。
	 * 
	 *  调用 codex-rs 的 `command/exec/terminate` 方法，终止指定进程 ID
	 *  对应的运行中命令会话。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `processId`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `processId` 为空
	 */
	commandExecTerminate: (args: CommandExecTerminateArgs) => typedError<string, AppError>(__TAURI_INVOKE("command_exec_terminate", { args })),
	/**
	 *  调整 PTY 终端大小。
	 * 
	 *  调用 codex-rs 的 `command/exec/resize` 方法，调整 PTY 模式下
	 *  运行中的命令会话的终端大小。params 中的 `size` 字段是嵌套对象，
	 *  包含 `rows` 和 `cols`。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `processId`、`rows` 和 `cols`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `processId` 为空或 `rows`/`cols` 为 0
	 */
	commandExecResize: (args: CommandExecResizeArgs) => typedError<string, AppError>(__TAURI_INVOKE("command_exec_resize", { args })),
	/**
	 *  列出可用插件。
	 * 
	 *  调用 codex-rs 的 `plugin/list` 方法，返回所有可用插件列表。
	 *  可通过 `cwds` 和 `marketplaceKinds` 过滤。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含可选的 `cwds` 和 `marketplaceKinds`
	 */
	pluginList: (args: PluginListArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("plugin_list", { args })),
	/**
	 *  安装插件。
	 * 
	 *  调用 codex-rs 的 `plugin/install` 方法，从指定市场安装插件。
	 *  `marketplacePath` 和 `remoteMarketplaceName` 二选一。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `pluginName` 和可选的 `marketplacePath` 或 `remoteMarketplaceName`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `pluginName` 为空
	 */
	pluginInstall: (args: PluginInstallArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("plugin_install", { args })),
	/**
	 *  卸载插件。
	 * 
	 *  调用 codex-rs 的 `plugin/uninstall` 方法，卸载指定 ID 的插件。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `pluginId`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `pluginId` 为空
	 */
	pluginUninstall: (args: PluginUninstallArgs) => typedError<string, AppError>(__TAURI_INVOKE("plugin_uninstall", { args })),
	/**
	 *  读取插件详情。
	 * 
	 *  调用 codex-rs 的 `plugin/read` 方法，获取指定插件的详细信息。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `pluginName` 和可选的 `marketplacePath` 或 `remoteMarketplaceName`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `pluginName` 为空
	 */
	pluginRead: (args: PluginReadArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("plugin_read", { args })),
	/**
	 *  启动独立进程。
	 * 
	 *  调用 codex-rs 的 `process/spawn` 方法，在主机上启动一个独立进程。
	 *  与 `command/exec` 不同，此命令不经过 Codex 沙箱。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 进程参数（argv 向量、进程句柄、工作目录等）
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `command` 为空或 `processHandle`/`cwd` 为空
	 */
	processSpawn: (args: ProcessSpawnArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("process_spawn", { args })),
	/**
	 *  写入 stdin 或关闭 stdin。
	 * 
	 *  调用 codex-rs 的 `process/writeStdin` 方法，向正在运行的
	 *  `process/spawn` 会话写入 base64 编码的 stdin 数据，或关闭 stdin。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `processHandle` 和可选的 `deltaBase64`、`closeStdin`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `processHandle` 为空
	 */
	processWriteStdin: (args: ProcessWriteStdinArgs_Deserialize) => typedError<string, AppError>(__TAURI_INVOKE("process_write_stdin", { args })),
	/**
	 *  终止运行中的进程。
	 * 
	 *  调用 codex-rs 的 `process/kill` 方法，终止指定进程句柄对应的
	 *  运行中进程。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `processHandle`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `processHandle` 为空
	 */
	processKill: (args: ProcessKillArgs) => typedError<string, AppError>(__TAURI_INVOKE("process_kill", { args })),
	/**
	 *  调整 PTY 终端大小。
	 * 
	 *  调用 codex-rs 的 `process/resizePty` 方法，调整 PTY 模式下
	 *  运行中的进程的终端大小。params 中的 `size` 字段是嵌套对象，
	 *  包含 `rows` 和 `cols`。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `processHandle`、`rows` 和 `cols`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — `processHandle` 为空或 `rows`/`cols` 为 0
	 */
	processResizePty: (args: ProcessResizePtyArgs) => typedError<string, AppError>(__TAURI_INVOKE("process_resize_pty", { args })),
	/**
	 *  批准一个 pending server request。
	 * 
	 *  从全局 pending 存储中取出 request（如果存在），
	 *  然后通过 `sender.respond_to_server_request` 将 JSON-RPC result
	 *  回传给 codex-rs，使其继续执行被审批的操作。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `request_id_json` 和 `result_json`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — JSON 反序列化失败
	 *  - [`AppError::NotInitialized`] — codex 运行时未初始化
	 *  - [`AppError::NotFound`] — request_id 不在 pending 存储中（已响应或从未注册）
	 *  - [`AppError::AppServerError`] — 回传响应时传输失败
	 */
	approvalRespond: (args: ApprovalRespondArgs) => typedError<null, AppError>(__TAURI_INVOKE("approval_respond", { args })),
	/**
	 *  拒绝一个 pending server request。
	 * 
	 *  从全局 pending 存储中取出 request，然后通过
	 *  `sender.fail_server_request` 将 JSON-RPC error 回传给 codex-rs，
	 *  使其中止被拒绝的操作。
	 * 
	 *  # 参数
	 * 
	 *  - `args` — 包含 `request_id_json` 和 `error_json`
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Validation`] — JSON 反序列化失败
	 *  - [`AppError::NotInitialized`] — codex 运行时未初始化
	 *  - [`AppError::NotFound`] — request_id 不在 pending 存储中
	 *  - [`AppError::AppServerError`] — 回传错误时传输失败
	 */
	approvalReject: (args: ApprovalRejectArgs) => typedError<null, AppError>(__TAURI_INVOKE("approval_reject", { args })),
	/**
	 *  列出所有 pending approval request 的 ID。
	 * 
	 *  前端在页面刷新后可以调用此命令，恢复审批对话框。
	 *  返回的 ID 列表对应尚未响应的 `ServerRequest`。
	 * 
	 *  # 返回
	 * 
	 *  返回 JSON 字符串，反序列化后为 `RequestId[]`。
	 *  例如：`"[1, 2, 3]"`（整数 ID 列表）。
	 * 
	 *  # 错误
	 * 
	 *  - [`AppError::Serialization`] — 序列化失败（理论上不应发生）
	 */
	approvalListPending: () => typedError<string, AppError>(__TAURI_INVOKE("approval_list_pending")),
};

/* Types */
/**
 *  所有 Tauri 命令处理器使用的统一错误类型。
 * 
 *  每个变体对应一类宽泛的失败场景。`kind` 标签允许前端按错误类型 switch，
 *  `message` 字段则承载人类可读的详细信息。
 * 
 *  ## P1-4 脱敏设计
 * 
 *  `Display` 和 `Serialize` 的输出经过 `redact_error_message` 处理：
 *  1. 键值对模式（`api_key=xxx`）→ `api_key=***`
 *  2. 值模式（`sk-xxx`、`AKIAxxx`、`Bearer xxx`）→ 脱敏
 *  3. 超长消息（>1000 字节）→ 截断 + `...` 后缀
 * 
 *  这确保错误消息通过日志、Sentry、Tauri IPC 传输时不会泄露敏感数据。
 *  `Debug` 和 `Clone` 自动派生，`serde::Deserialize` 派生以让 `#[serde(...)]` 属性
 *  合法（specta 读取此属性生成正确的 TS 类型），`specta::Type` 用于生成 TypeScript 绑定。
 *  `Serialize` 手动实现以在输出前调用 `redact_error_message` 脱敏。
 */
export type AppError = 
/**  文件系统或 I/O 错误。 */
{ kind: "Io"; message: string } | 
/**  JSON 序列化/反序列化错误。 */
{ kind: "Serialization"; message: string } | 
/**  路径解析错误（例如找不到应用数据目录）。 */
{ kind: "Path"; message: string } | 
/**  输入校验错误。 */
{ kind: "Validation"; message: string } | 
/**  资源未找到。 */
{ kind: "NotFound"; message: string } | 
/**  `spawn_blocking` 产生的任务 join 错误。 */
{ kind: "TaskJoin"; message: string } | 
/**  托盘图标操作错误。 */
{ kind: "Tray"; message: string } | 
/**  快捷面板操作错误。 */
{ kind: "QuickPane"; message: string } | 
/**  通知错误。 */
{ kind: "Notification"; message: string } | 
/**  窗口操作错误。 */
{ kind: "Window"; message: string } | 
/**  Codex 运行时启动失败。 */
{ kind: "RuntimeStart"; message: string } | 
/**  Codex 运行时未能正常关闭。 */
{ kind: "RuntimeShutdown"; message: string } | 
/**  Codex 运行时未初始化 —— 在 `setup()` 之前调用了命令。 */
{ kind: "NotInitialized"; message: string } | 
/**  Codex app-server 返回了错误。 */
{ kind: "AppServerError"; message: string } | 
/**
 *  发往 app-server 的类型化请求失败（传输、服务端错误或响应解码失败）。
 *  由 [`TypedRequestError`] 转换而来。
 */
{ kind: "TypedRequestError"; message: string };

/**
 *  用户偏好设置，会持久化到磁盘（`preferences.json`）。
 * 
 *  仅包含需要在会话之间保留的设置项。所有字段都通过 tauri-specta
 *  暴露给前端，前端可直接读写这些字段。
 */
export type AppPreferences = {
	/**
	 *  UI 主题模式：`"light"`、`"dark"` 或 `"system"`（跟随系统）。
	 * 
	 *  缺失时使用 `default_theme()` 填充 `"system"`。
	 */
	theme?: string,
	/**
	 *  快速面板的全局快捷键（如 `"CommandOrControl+Shift+."`）。
	 * 
	 *  若为 `None`，使用 [`DEFAULT_QUICK_PANE_SHORTCUT`] 默认值。
	 */
	quick_pane_shortcut: string | null,
	/**
	 *  用户偏好的界面语言代码（如 `"en"`、`"zh"`、`"ja"`）。
	 * 
	 *  若为 `None`，使用系统区域设置自动检测。
	 */
	language: string | null,
	/**
	 *  崩溃报告授权状态：
	 *  - `None`：尚未询问用户
	 *  - `Some(true)`：用户已授权
	 *  - `Some(false)`：用户已拒绝
	 */
	crash_reporting_consent: boolean | null,
};

/**
 *  `approval/reject` 命令的参数。
 * 
 *  拒绝一个 pending server request，将 JSON-RPC error 回传给 codex-rs。
 */
export type ApprovalRejectArgs = {
	/**
	 *  要拒绝的 request ID（JSON 序列化后的字符串）。
	 *  格式同 [`ApprovalRespondArgs::request_id_json`]。
	 */
	requestIdJson: string,
	/**
	 *  JSON-RPC error 对象（JSON 字符串）。
	 * 
	 *  格式：`{ "code": -32601, "message": "...", "data": null }`
	 * 
	 *  常用错误码：
	 *  - `-32601` — Method not found
	 *  - `-32602` — Invalid params
	 *  - `-32603` — Internal error
	 *  - `-32000` — Server error（通用）
	 * 
	 *  前端通过 `JSON.stringify(error)` 传入。
	 */
	errorJson: string,
};

/**
 *  `approval/respond` 命令的参数。
 * 
 *  批准一个 pending server request，将 JSON-RPC result 回传给 codex-rs。
 */
export type ApprovalRespondArgs = {
	/**
	 *  要批准的 request ID（JSON 序列化后的字符串）。
	 * 
	 *  前端通过 `JSON.stringify(requestId)` 生成。
	 *  `RequestId` 是枚举类型（`Integer(i64)` 或 `String(String)`），
	 *  序列化后为 JSON 数字或 JSON 字符串。
	 * 
	 *  **示例**：
	 *  - 整数 ID 42 → `requestIdJson = "42"`
	 *  - 字符串 ID "abc" → `requestIdJson = "\"abc\""`
	 */
	requestIdJson: string,
	/**
	 *  JSON-RPC result payload（JSON 字符串）。
	 * 
	 *  具体结构取决于 `ServerRequest` 类型。例如：
	 *  - `CommandExecutionRequestApproval` → `{ "approved": true }`
	 *  - `FileChangeRequestApproval` → `{ "approved": true }`
	 *  - `CurrentTimeRead` → `{ "time": "2026-01-01T00:00:00Z" }`
	 * 
	 *  前端构造好 result 对象后通过 `JSON.stringify(result)` 传入。
	 */
	resultJson: string,
};

/**  `account/login/cancel` 命令的参数。 */
export type CancelLoginAccountArgs = {
	/**  要取消的登录会话 ID（必填）。 */
	loginId: string,
};

/**
 *  `command/exec` 命令的参数。
 * 
 *  在服务器沙箱内执行一个独立的命令（argv 向量）。
 */
export type CommandExecArgs = CommandExecArgs_Serialize | CommandExecArgs_Deserialize;

/**
 *  `command/exec` 命令的参数。
 * 
 *  在服务器沙箱内执行一个独立的命令（argv 向量）。
 */
export type CommandExecArgs_Deserialize = {
	/**  命令 argv 向量（如 `["ls", "-la"]`，必填，不能为空）。 */
	command: string[],
	/**  客户端提供的进程 ID，用于后续的 write/terminate/resize 调用。 */
	processId?: string | null,
	/**  是否启用 PTY 模式。启用后隐含 streamStdin 和 streamStdoutStderr。 */
	tty?: boolean | null,
	/**  是否允许后续 `command/exec/write` 写入 stdin。 */
	streamStdin?: boolean | null,
	/**  是否通过通知流式传输 stdout/stderr。 */
	streamStdoutStderr?: boolean | null,
	/**  工作目录。为空时使用服务器默认值。 */
	cwd?: string | null,
	/**  超时时间（毫秒）。为空时使用服务器默认值。 */
	timeoutMs?: number | null,
};

/**
 *  `command/exec` 命令的参数。
 * 
 *  在服务器沙箱内执行一个独立的命令（argv 向量）。
 */
export type CommandExecArgs_Serialize = {
	/**  命令 argv 向量（如 `["ls", "-la"]`，必填，不能为空）。 */
	command: string[],
	/**  客户端提供的进程 ID，用于后续的 write/terminate/resize 调用。 */
	processId?: string | null,
	/**  是否启用 PTY 模式。启用后隐含 streamStdin 和 streamStdoutStderr。 */
	tty?: boolean | null,
	/**  是否允许后续 `command/exec/write` 写入 stdin。 */
	streamStdin?: boolean | null,
	/**  是否通过通知流式传输 stdout/stderr。 */
	streamStdoutStderr?: boolean | null,
	/**  工作目录。为空时使用服务器默认值。 */
	cwd?: string | null,
	/**  超时时间（毫秒）。为空时使用服务器默认值。 */
	timeoutMs?: number | null,
};

/**
 *  `command/exec/resize` 命令的参数。
 * 
 *  调整 PTY 模式下运行中的命令会话终端大小。
 */
export type CommandExecResizeArgs = {
	/**  要调整大小的进程 ID（必填）。 */
	processId: string,
	/**  终端行数（高度）。 */
	rows: number,
	/**  终端列数（宽度）。 */
	cols: number,
};

/**  `command/exec/terminate` 命令的参数。 */
export type CommandExecTerminateArgs = {
	/**  要终止的进程 ID（必填）。 */
	processId: string,
};

/**
 *  `command/exec/write` 命令的参数。
 * 
 *  向正在运行的 `command/exec` 会话写入 stdin 数据或关闭 stdin。
 */
export type CommandExecWriteArgs = CommandExecWriteArgs_Serialize | CommandExecWriteArgs_Deserialize;

/**
 *  `command/exec/write` 命令的参数。
 * 
 *  向正在运行的 `command/exec` 会话写入 stdin 数据或关闭 stdin。
 */
export type CommandExecWriteArgs_Deserialize = {
	/**  客户端提供的进程 ID（必填）。 */
	processId: string,
	/**  要写入的 stdin 数据，base64 编码。 */
	deltaBase64?: string | null,
	/**  写入后是否关闭 stdin。 */
	closeStdin?: boolean | null,
};

/**
 *  `command/exec/write` 命令的参数。
 * 
 *  向正在运行的 `command/exec` 会话写入 stdin 数据或关闭 stdin。
 */
export type CommandExecWriteArgs_Serialize = {
	/**  客户端提供的进程 ID（必填）。 */
	processId: string,
	/**  要写入的 stdin 数据，base64 编码。 */
	deltaBase64?: string | null,
	/**  写入后是否关闭 stdin。 */
	closeStdin?: boolean | null,
};

/**
 *  `config/batchWrite` 命令的参数。
 * 
 *  批量写入多个配置项到指定文件。
 * 
 *  `edits` 为 `Vec<ConfigEdit>` 的 JSON 字符串，由前端 `JSON.stringify` 后传入。
 *  使用 `String` 而非 `serde_json::Value` 是为了规避 specta BigInt 禁令。
 */
export type ConfigBatchWriteArgs = ConfigBatchWriteArgs_Serialize | ConfigBatchWriteArgs_Deserialize;

/**
 *  `config/batchWrite` 命令的参数。
 * 
 *  批量写入多个配置项到指定文件。
 * 
 *  `edits` 为 `Vec<ConfigEdit>` 的 JSON 字符串，由前端 `JSON.stringify` 后传入。
 *  使用 `String` 而非 `serde_json::Value` 是为了规避 specta BigInt 禁令。
 */
export type ConfigBatchWriteArgs_Deserialize = {
	/**  批量编辑列表的 JSON 字符串（前端 `JSON.stringify` 后传入，是 `Vec<ConfigEdit>` 数组）。 */
	edits: string,
	/**  目标配置文件路径。为空时写入用户默认 config.toml。 */
	filePath?: string | null,
};

/**
 *  `config/batchWrite` 命令的参数。
 * 
 *  批量写入多个配置项到指定文件。
 * 
 *  `edits` 为 `Vec<ConfigEdit>` 的 JSON 字符串，由前端 `JSON.stringify` 后传入。
 *  使用 `String` 而非 `serde_json::Value` 是为了规避 specta BigInt 禁令。
 */
export type ConfigBatchWriteArgs_Serialize = {
	/**  批量编辑列表的 JSON 字符串（前端 `JSON.stringify` 后传入，是 `Vec<ConfigEdit>` 数组）。 */
	edits: string,
	/**  目标配置文件路径。为空时写入用户默认 config.toml。 */
	filePath?: string | null,
};

/**
 *  `config/read` 命令的参数。
 * 
 *  读取当前生效的配置，可选是否包含各配置层详情和工作目录上下文。
 */
export type ConfigReadArgs = ConfigReadArgs_Serialize | ConfigReadArgs_Deserialize;

/**
 *  `config/read` 命令的参数。
 * 
 *  读取当前生效的配置，可选是否包含各配置层详情和工作目录上下文。
 */
export type ConfigReadArgs_Deserialize = {
	/**  是否包含各配置层（layers）详情。默认 false。 */
	includeLayers?: boolean | null,
	/**  工作目录，用于解析项目配置层。为空时使用服务器默认值。 */
	cwd?: string | null,
};

/**
 *  `config/read` 命令的参数。
 * 
 *  读取当前生效的配置，可选是否包含各配置层详情和工作目录上下文。
 */
export type ConfigReadArgs_Serialize = {
	/**  是否包含各配置层（layers）详情。默认 false。 */
	includeLayers?: boolean | null,
	/**  工作目录，用于解析项目配置层。为空时使用服务器默认值。 */
	cwd?: string | null,
};

/**
 *  `config/value/write` 命令的参数。
 * 
 *  写入单个配置项到指定文件（默认为用户 config.toml）。
 * 
 *  `value` 为 JSON 值的字符串表示，由前端 `JSON.stringify` 后传入。
 *  使用 `String` 而非 `serde_json::Value` 是为了规避 specta BigInt 禁令。
 */
export type ConfigValueWriteArgs = ConfigValueWriteArgs_Serialize | ConfigValueWriteArgs_Deserialize;

/**
 *  `config/value/write` 命令的参数。
 * 
 *  写入单个配置项到指定文件（默认为用户 config.toml）。
 * 
 *  `value` 为 JSON 值的字符串表示，由前端 `JSON.stringify` 后传入。
 *  使用 `String` 而非 `serde_json::Value` 是为了规避 specta BigInt 禁令。
 */
export type ConfigValueWriteArgs_Deserialize = {
	/**  配置键路径（如 `"model"`、`"tools.webSearch"`，必填）。 */
	keyPath: string,
	/**  配置值的 JSON 字符串（前端 `JSON.stringify` 后传入）。 */
	value: string,
	/**  合并策略：`"replace"` 或 `"upsert"`（必填）。 */
	mergeStrategy: string,
	/**  目标配置文件路径。为空时写入用户默认 config.toml。 */
	filePath?: string | null,
};

/**
 *  `config/value/write` 命令的参数。
 * 
 *  写入单个配置项到指定文件（默认为用户 config.toml）。
 * 
 *  `value` 为 JSON 值的字符串表示，由前端 `JSON.stringify` 后传入。
 *  使用 `String` 而非 `serde_json::Value` 是为了规避 specta BigInt 禁令。
 */
export type ConfigValueWriteArgs_Serialize = {
	/**  配置键路径（如 `"model"`、`"tools.webSearch"`，必填）。 */
	keyPath: string,
	/**  配置值的 JSON 字符串（前端 `JSON.stringify` 后传入）。 */
	value: string,
	/**  合并策略：`"replace"` 或 `"upsert"`（必填）。 */
	mergeStrategy: string,
	/**  目标配置文件路径。为空时写入用户默认 config.toml。 */
	filePath?: string | null,
};

/**
 *  崩溃报告数据，由 panic hook 捕获并写入磁盘。
 * 
 *  应用下次启动时，前端会读取此数据并在用户已授权的情况下发送给 Sentry。
 *  JSON 文件路径由 [`crate::commands::crash_report`] 模块管理。
 */
export type CrashReportData = {
	/**  崩溃类型标识（当前固定为 `"rust_panic"`） */
	crash_type: string,
	/**  panic 消息文本（已脱敏） */
	message: string,
	/**  源码位置（`文件:行号:列号`），可能为 `None` */
	location: string | null,
	/**  完整的调用栈回溯字符串（已脱敏） */
	backtrace: string,
	/**  Unix 时间戳（自 epoch 起的秒数，浮点数） */
	timestamp: number | null,
	/**  崩溃发生时的应用版本号 */
	app_version: string,
};

/**  `fs/copy` 命令的参数。 */
export type FsCopyArgs = FsCopyArgs_Serialize | FsCopyArgs_Deserialize;

/**  `fs/copy` 命令的参数。 */
export type FsCopyArgs_Deserialize = {
	/**  源文件绝对路径（必填）。 */
	sourcePath: string,
	/**  目标文件绝对路径（必填）。 */
	destinationPath: string,
	/**  复制目录时是否递归。默认 false。 */
	recursive?: boolean | null,
};

/**  `fs/copy` 命令的参数。 */
export type FsCopyArgs_Serialize = {
	/**  源文件绝对路径（必填）。 */
	sourcePath: string,
	/**  目标文件绝对路径（必填）。 */
	destinationPath: string,
	/**  复制目录时是否递归。默认 false。 */
	recursive?: boolean | null,
};

/**  `fs/createDirectory` 命令的参数。 */
export type FsCreateDirectoryArgs = FsCreateDirectoryArgs_Serialize | FsCreateDirectoryArgs_Deserialize;

/**  `fs/createDirectory` 命令的参数。 */
export type FsCreateDirectoryArgs_Deserialize = {
	/**  要创建的目录绝对路径（必填）。 */
	path: string,
	/**  是否递归创建父目录。默认 true。 */
	recursive?: boolean | null,
};

/**  `fs/createDirectory` 命令的参数。 */
export type FsCreateDirectoryArgs_Serialize = {
	/**  要创建的目录绝对路径（必填）。 */
	path: string,
	/**  是否递归创建父目录。默认 true。 */
	recursive?: boolean | null,
};

/**  `fs/getMetadata` 命令的参数。 */
export type FsGetMetadataArgs = {
	/**  要查询元数据的路径（必填）。 */
	path: string,
};

/**  `fs/readDirectory` 命令的参数。 */
export type FsReadDirectoryArgs = {
	/**  要列出的目录绝对路径（必填）。 */
	path: string,
};

/**  `fs/readFile` 命令的参数。 */
export type FsReadFileArgs = {
	/**  要读取的文件绝对路径（必填）。 */
	path: string,
};

/**  `fs/remove` 命令的参数。 */
export type FsRemoveArgs = FsRemoveArgs_Serialize | FsRemoveArgs_Deserialize;

/**  `fs/remove` 命令的参数。 */
export type FsRemoveArgs_Deserialize = {
	/**  要删除的路径（必填）。 */
	path: string,
	/**  是否递归删除目录。默认 true。 */
	recursive?: boolean | null,
	/**  路径不存在时是否忽略。默认 true。 */
	force?: boolean | null,
};

/**  `fs/remove` 命令的参数。 */
export type FsRemoveArgs_Serialize = {
	/**  要删除的路径（必填）。 */
	path: string,
	/**  是否递归删除目录。默认 true。 */
	recursive?: boolean | null,
	/**  路径不存在时是否忽略。默认 true。 */
	force?: boolean | null,
};

/**  `fs/unwatch` 命令的参数。 */
export type FsUnwatchArgs = {
	/**  之前通过 `fs/watch` 注册的监听标识符（必填）。 */
	watchId: string,
};

/**  `fs/watch` 命令的参数。 */
export type FsWatchArgs = {
	/**  连接作用域内的监听标识符，用于后续的 `fs/unwatch`（必填）。 */
	watchId: string,
	/**  要监听的文件或目录绝对路径（必填）。 */
	path: string,
};

/**  `fs/writeFile` 命令的参数。 */
export type FsWriteFileArgs = {
	/**  要写入的文件绝对路径（必填）。 */
	path: string,
	/**  文件内容，base64 编码（必填）。 */
	dataBase64: string,
};

/**  `account/read` 命令的参数。 */
export type GetAccountArgs = GetAccountArgs_Serialize | GetAccountArgs_Deserialize;

/**  `account/read` 命令的参数。 */
export type GetAccountArgs_Deserialize = {
	/**  是否在返回前主动刷新令牌。默认 false。 */
	refreshToken?: boolean | null,
};

/**  `account/read` 命令的参数。 */
export type GetAccountArgs_Serialize = {
	/**  是否在返回前主动刷新令牌。默认 false。 */
	refreshToken?: boolean | null,
};

/**
 *  `account/login/start` 命令的参数。
 * 
 *  支持三种登录方式：
 *  - `"apiKey"` — 使用 API Key 登录（需提供 `apiKey`）
 *  - `"chatgpt"` — 使用 ChatGPT OAuth 登录
 *  - `"chatgptDeviceCode"` — 使用 ChatGPT 设备码登录
 */
export type LoginAccountArgs = LoginAccountArgs_Serialize | LoginAccountArgs_Deserialize;

/**
 *  `account/login/start` 命令的参数。
 * 
 *  支持三种登录方式：
 *  - `"apiKey"` — 使用 API Key 登录（需提供 `apiKey`）
 *  - `"chatgpt"` — 使用 ChatGPT OAuth 登录
 *  - `"chatgptDeviceCode"` — 使用 ChatGPT 设备码登录
 */
export type LoginAccountArgs_Deserialize = {
	/**  登录类型：`"apiKey"`、`"chatgpt"` 或 `"chatgptDeviceCode"`（必填）。 */
	loginType: string,
	/**  API Key（仅 `login_type = "apiKey"` 时需要）。 */
	apiKey?: string | null,
};

/**
 *  `account/login/start` 命令的参数。
 * 
 *  支持三种登录方式：
 *  - `"apiKey"` — 使用 API Key 登录（需提供 `apiKey`）
 *  - `"chatgpt"` — 使用 ChatGPT OAuth 登录
 *  - `"chatgptDeviceCode"` — 使用 ChatGPT 设备码登录
 */
export type LoginAccountArgs_Serialize = {
	/**  登录类型：`"apiKey"`、`"chatgpt"` 或 `"chatgptDeviceCode"`（必填）。 */
	loginType: string,
	/**  API Key（仅 `login_type = "apiKey"` 时需要）。 */
	apiKey?: string | null,
};

/**  `account/logout` 命令的参数（无字段）。 */
export type LogoutAccountArgs = Record<string, never>;

/**
 *  `mcpServer/resource/read` 命令的参数。
 * 
 *  读取指定 MCP 服务器上的资源内容。
 */
export type McpResourceReadArgs = McpResourceReadArgs_Serialize | McpResourceReadArgs_Deserialize;

/**
 *  `mcpServer/resource/read` 命令的参数。
 * 
 *  读取指定 MCP 服务器上的资源内容。
 */
export type McpResourceReadArgs_Deserialize = {
	/**  关联的线程 ID。为空时使用全局作用域。 */
	threadId?: string | null,
	/**  MCP 服务器名称（必填）。 */
	server: string,
	/**  资源 URI（必填）。 */
	uri: string,
};

/**
 *  `mcpServer/resource/read` 命令的参数。
 * 
 *  读取指定 MCP 服务器上的资源内容。
 */
export type McpResourceReadArgs_Serialize = {
	/**  关联的线程 ID。为空时使用全局作用域。 */
	threadId?: string | null,
	/**  MCP 服务器名称（必填）。 */
	server: string,
	/**  资源 URI（必填）。 */
	uri: string,
};

/**
 *  `mcpServer/oauth/login` 命令的参数。
 * 
 *  启动指定 MCP 服务器的 OAuth 登录流程。
 */
export type McpServerOauthLoginArgs = McpServerOauthLoginArgs_Serialize | McpServerOauthLoginArgs_Deserialize;

/**
 *  `mcpServer/oauth/login` 命令的参数。
 * 
 *  启动指定 MCP 服务器的 OAuth 登录流程。
 */
export type McpServerOauthLoginArgs_Deserialize = {
	/**  MCP 服务器名称（必填）。 */
	name: string,
	/**  关联的线程 ID。为空时使用全局作用域。 */
	threadId?: string | null,
	/**  OAuth 授权范围列表。 */
	scopes?: string[] | null,
	/**  登录超时时间（秒）。 */
	timeoutSecs?: number | null,
};

/**
 *  `mcpServer/oauth/login` 命令的参数。
 * 
 *  启动指定 MCP 服务器的 OAuth 登录流程。
 */
export type McpServerOauthLoginArgs_Serialize = {
	/**  MCP 服务器名称（必填）。 */
	name: string,
	/**  关联的线程 ID。为空时使用全局作用域。 */
	threadId?: string | null,
	/**  OAuth 授权范围列表。 */
	scopes?: string[] | null,
	/**  登录超时时间（秒）。 */
	timeoutSecs?: number | null,
};

/**
 *  `config/mcpServer/reload` 命令的参数（无字段）。
 * 
 *  刷新 MCP 服务器配置，重新加载所有已注册的 MCP 服务器。
 */
export type McpServerRefreshArgs = Record<string, never>;

/**
 *  `mcpServerStatus/list` 命令的参数。
 * 
 *  分页列出所有 MCP 服务器的状态信息。
 */
export type McpServerStatusListArgs = McpServerStatusListArgs_Serialize | McpServerStatusListArgs_Deserialize;

/**
 *  `mcpServerStatus/list` 命令的参数。
 * 
 *  分页列出所有 MCP 服务器的状态信息。
 */
export type McpServerStatusListArgs_Deserialize = {
	/**  分页游标。 */
	cursor?: string | null,
	/**  每页数量。 */
	limit?: number | null,
	/**  关联的线程 ID。 */
	threadId?: string | null,
};

/**
 *  `mcpServerStatus/list` 命令的参数。
 * 
 *  分页列出所有 MCP 服务器的状态信息。
 */
export type McpServerStatusListArgs_Serialize = {
	/**  分页游标。 */
	cursor?: string | null,
	/**  每页数量。 */
	limit?: number | null,
	/**  关联的线程 ID。 */
	threadId?: string | null,
};

/**
 *  `mcpServer/tool/call` 命令的参数。
 * 
 *  调用指定 MCP 服务器上的工具。
 * 
 *  `arguments` 为工具调用参数的 JSON 字符串，由前端 `JSON.stringify` 后传入。
 *  使用 `String` 而非 `serde_json::Value` 是为了规避 specta BigInt 禁令。
 */
export type McpServerToolCallArgs = McpServerToolCallArgs_Serialize | McpServerToolCallArgs_Deserialize;

/**
 *  `mcpServer/tool/call` 命令的参数。
 * 
 *  调用指定 MCP 服务器上的工具。
 * 
 *  `arguments` 为工具调用参数的 JSON 字符串，由前端 `JSON.stringify` 后传入。
 *  使用 `String` 而非 `serde_json::Value` 是为了规避 specta BigInt 禁令。
 */
export type McpServerToolCallArgs_Deserialize = {
	/**  关联的线程 ID（必填）。 */
	threadId: string,
	/**  MCP 服务器名称（必填）。 */
	server: string,
	/**  要调用的工具名称（必填）。 */
	tool: string,
	/**  工具调用参数的 JSON 字符串（前端 `JSON.stringify` 后传入，是一个 JSON 对象）。 */
	arguments?: string | null,
};

/**
 *  `mcpServer/tool/call` 命令的参数。
 * 
 *  调用指定 MCP 服务器上的工具。
 * 
 *  `arguments` 为工具调用参数的 JSON 字符串，由前端 `JSON.stringify` 后传入。
 *  使用 `String` 而非 `serde_json::Value` 是为了规避 specta BigInt 禁令。
 */
export type McpServerToolCallArgs_Serialize = {
	/**  关联的线程 ID（必填）。 */
	threadId: string,
	/**  MCP 服务器名称（必填）。 */
	server: string,
	/**  要调用的工具名称（必填）。 */
	tool: string,
	/**  工具调用参数的 JSON 字符串（前端 `JSON.stringify` 后传入，是一个 JSON 对象）。 */
	arguments?: string | null,
};

/**
 *  `plugin/install` 命令的参数。
 * 
 *  安装指定插件。
 */
export type PluginInstallArgs = PluginInstallArgs_Serialize | PluginInstallArgs_Deserialize;

/**
 *  `plugin/install` 命令的参数。
 * 
 *  安装指定插件。
 */
export type PluginInstallArgs_Deserialize = {
	/**  本地市场路径。与 `remoteMarketplaceName` 互斥。 */
	marketplacePath?: string | null,
	/**  远程市场名称。与 `marketplacePath` 互斥。 */
	remoteMarketplaceName?: string | null,
	/**  要安装的插件名称（必填）。 */
	pluginName: string,
};

/**
 *  `plugin/install` 命令的参数。
 * 
 *  安装指定插件。
 */
export type PluginInstallArgs_Serialize = {
	/**  本地市场路径。与 `remoteMarketplaceName` 互斥。 */
	marketplacePath?: string | null,
	/**  远程市场名称。与 `marketplacePath` 互斥。 */
	remoteMarketplaceName?: string | null,
	/**  要安装的插件名称（必填）。 */
	pluginName: string,
};

/**
 *  `plugin/list` 命令的参数。
 * 
 *  列出可用的插件，可按工作目录和市场类型过滤。
 */
export type PluginListArgs = PluginListArgs_Serialize | PluginListArgs_Deserialize;

/**
 *  `plugin/list` 命令的参数。
 * 
 *  列出可用的插件，可按工作目录和市场类型过滤。
 */
export type PluginListArgs_Deserialize = {
	/**  工作目录列表，用于发现仓库级市场。 */
	cwds?: string[] | null,
	/**  市场类型过滤（如 `"local"`、`"remote"`）。 */
	marketplaceKinds?: string[] | null,
};

/**
 *  `plugin/list` 命令的参数。
 * 
 *  列出可用的插件，可按工作目录和市场类型过滤。
 */
export type PluginListArgs_Serialize = {
	/**  工作目录列表，用于发现仓库级市场。 */
	cwds?: string[] | null,
	/**  市场类型过滤（如 `"local"`、`"remote"`）。 */
	marketplaceKinds?: string[] | null,
};

/**
 *  `plugin/read` 命令的参数。
 * 
 *  读取指定插件的详细信息。
 */
export type PluginReadArgs = PluginReadArgs_Serialize | PluginReadArgs_Deserialize;

/**
 *  `plugin/read` 命令的参数。
 * 
 *  读取指定插件的详细信息。
 */
export type PluginReadArgs_Deserialize = {
	/**  本地市场路径。与 `remoteMarketplaceName` 互斥。 */
	marketplacePath?: string | null,
	/**  远程市场名称。与 `marketplacePath` 互斥。 */
	remoteMarketplaceName?: string | null,
	/**  要读取的插件名称（必填）。 */
	pluginName: string,
};

/**
 *  `plugin/read` 命令的参数。
 * 
 *  读取指定插件的详细信息。
 */
export type PluginReadArgs_Serialize = {
	/**  本地市场路径。与 `remoteMarketplaceName` 互斥。 */
	marketplacePath?: string | null,
	/**  远程市场名称。与 `marketplacePath` 互斥。 */
	remoteMarketplaceName?: string | null,
	/**  要读取的插件名称（必填）。 */
	pluginName: string,
};

/**
 *  `plugin/uninstall` 命令的参数。
 * 
 *  卸载指定插件。
 */
export type PluginUninstallArgs = {
	/**  要卸载的插件 ID（必填）。 */
	pluginId: string,
};

/**
 *  `process/kill` 命令的参数。
 * 
 *  终止指定进程句柄对应的运行中进程。
 */
export type ProcessKillArgs = {
	/**  要终止的进程句柄（必填）。 */
	processHandle: string,
};

/**
 *  `process/resizePty` 命令的参数。
 * 
 *  调整 PTY 模式下运行中的进程终端大小。
 */
export type ProcessResizePtyArgs = {
	/**  要调整大小的进程句柄（必填）。 */
	processHandle: string,
	/**  终端行数（高度）。 */
	rows: number,
	/**  终端列数（宽度）。 */
	cols: number,
};

/**
 *  `process/spawn` 命令的参数。
 * 
 *  在主机上启动一个独立进程（argv 向量），不经过 Codex 沙箱。
 */
export type ProcessSpawnArgs = ProcessSpawnArgs_Serialize | ProcessSpawnArgs_Deserialize;

/**
 *  `process/spawn` 命令的参数。
 * 
 *  在主机上启动一个独立进程（argv 向量），不经过 Codex 沙箱。
 */
export type ProcessSpawnArgs_Deserialize = {
	/**  命令 argv 向量（如 `["node", "server.js"]`，必填，不能为空）。 */
	command: string[],
	/**  客户端提供的进程句柄，用于后续的 writeStdin/kill/resizePty 调用（必填）。 */
	processHandle: string,
	/**  绝对工作目录（必填）。 */
	cwd: string,
	/**  是否启用 PTY 模式。启用后隐含 streamStdin 和 streamStdoutStderr。 */
	tty?: boolean | null,
	/**  是否允许后续 `process/writeStdin` 写入 stdin。 */
	streamStdin?: boolean | null,
	/**  是否通过通知流式传输 stdout/stderr。 */
	streamStdoutStderr?: boolean | null,
};

/**
 *  `process/spawn` 命令的参数。
 * 
 *  在主机上启动一个独立进程（argv 向量），不经过 Codex 沙箱。
 */
export type ProcessSpawnArgs_Serialize = {
	/**  命令 argv 向量（如 `["node", "server.js"]`，必填，不能为空）。 */
	command: string[],
	/**  客户端提供的进程句柄，用于后续的 writeStdin/kill/resizePty 调用（必填）。 */
	processHandle: string,
	/**  绝对工作目录（必填）。 */
	cwd: string,
	/**  是否启用 PTY 模式。启用后隐含 streamStdin 和 streamStdoutStderr。 */
	tty?: boolean | null,
	/**  是否允许后续 `process/writeStdin` 写入 stdin。 */
	streamStdin?: boolean | null,
	/**  是否通过通知流式传输 stdout/stderr。 */
	streamStdoutStderr?: boolean | null,
};

/**
 *  `process/writeStdin` 命令的参数。
 * 
 *  向正在运行的 `process/spawn` 会话写入 stdin 数据或关闭 stdin。
 */
export type ProcessWriteStdinArgs = ProcessWriteStdinArgs_Serialize | ProcessWriteStdinArgs_Deserialize;

/**
 *  `process/writeStdin` 命令的参数。
 * 
 *  向正在运行的 `process/spawn` 会话写入 stdin 数据或关闭 stdin。
 */
export type ProcessWriteStdinArgs_Deserialize = {
	/**  客户端提供的进程句柄（必填）。 */
	processHandle: string,
	/**  要写入的 stdin 数据，base64 编码。 */
	deltaBase64?: string | null,
	/**  写入后是否关闭 stdin。 */
	closeStdin?: boolean | null,
};

/**
 *  `process/writeStdin` 命令的参数。
 * 
 *  向正在运行的 `process/spawn` 会话写入 stdin 数据或关闭 stdin。
 */
export type ProcessWriteStdinArgs_Serialize = {
	/**  客户端提供的进程句柄（必填）。 */
	processHandle: string,
	/**  要写入的 stdin 数据，base64 编码。 */
	deltaBase64?: string | null,
	/**  写入后是否关闭 stdin。 */
	closeStdin?: boolean | null,
};

/**
 *  恢复操作的错误类型，使用类型化变体以便前端精确匹配。
 * 
 *  使用 `tag = "kind"` 与 [`AppError`](crate::error::AppError) 的 serde tag 保持一致，
 *  前端可通过单一的 `kind` 判别字段处理所有错误类型。
 */
export type RecoveryError = 
/**  文件不存在（属于预期场景，非故障） */
{ kind: "FileNotFound" } | 
/**  文件名校验失败 */
{ kind: "ValidationError"; message: string } | 
/**  数据超出大小限制 */
{ kind: "DataTooLarge"; max_bytes: number } | 
/**  文件系统读写错误 */
{ kind: "IoError"; message: string } | 
/**  JSON 序列化/反序列化错误 */
{ kind: "ParseError"; message: string };

/**  `thread/approveGuardianDeniedAction` 命令的参数。 */
export type ThreadApproveGuardianDeniedActionArgs = {
	/**  线程 ID。 */
	threadId: string,
	/**  GuardianAssessmentEvent 的 JSON 字符串。 */
	eventJson: string,
};

/**  `thread/archive` 命令的参数。 */
export type ThreadArchiveArgs = {
	/**  要归档的线程 ID。 */
	threadId: string,
};

/**  `thread/backgroundTerminals/clean` 命令的参数。 */
export type ThreadBackgroundTerminalsCleanArgs = {
	/**  线程 ID。 */
	threadId: string,
};

/**  `thread/backgroundTerminals/list` 命令的参数。 */
export type ThreadBackgroundTerminalsListArgs = ThreadBackgroundTerminalsListArgs_Serialize | ThreadBackgroundTerminalsListArgs_Deserialize;

/**  `thread/backgroundTerminals/list` 命令的参数。 */
export type ThreadBackgroundTerminalsListArgs_Deserialize = {
	/**  线程 ID。 */
	threadId: string,
	/**  分页游标。 */
	cursor?: string | null,
	/**  每页数量。 */
	limit?: number | null,
};

/**  `thread/backgroundTerminals/list` 命令的参数。 */
export type ThreadBackgroundTerminalsListArgs_Serialize = {
	/**  线程 ID。 */
	threadId: string,
	/**  分页游标。 */
	cursor?: string | null,
	/**  每页数量。 */
	limit?: number | null,
};

/**  `thread/backgroundTerminals/terminate` 命令的参数。 */
export type ThreadBackgroundTerminalsTerminateArgs = {
	/**  线程 ID。 */
	threadId: string,
	/**  要终止的进程 ID。 */
	processId: string,
};

/**  `thread/compact/start` 命令的参数。 */
export type ThreadCompactStartArgs = {
	/**  线程 ID。 */
	threadId: string,
};

/**  `thread/decrement_elicitation` 命令的参数（experimental）。 */
export type ThreadDecrementElicitationArgs = {
	/**  线程 ID。 */
	threadId: string,
};

/**  `thread/delete` 命令的参数。 */
export type ThreadDeleteArgs = {
	/**  要删除的线程 ID。 */
	threadId: string,
};

/**
 *  `thread/fork` 命令的参数。
 * 
 *  协议层 ThreadForkParams 有 17 个字段，DTO 暴露常用字段 + params_json。
 */
export type ThreadForkArgs = ThreadForkArgs_Serialize | ThreadForkArgs_Deserialize;

/**
 *  `thread/fork` 命令的参数。
 * 
 *  协议层 ThreadForkParams 有 17 个字段，DTO 暴露常用字段 + params_json。
 */
export type ThreadForkArgs_Deserialize = {
	/**  要分叉的源线程 ID。 */
	threadId: string,
	/**  分叉点 turn ID（为空时取最后一个 turn）。 */
	lastTurnId?: string | null,
	/**  模型名称。 */
	model?: string | null,
	/**  模型提供商。 */
	modelProvider?: string | null,
	/**  工作目录。 */
	cwd?: string | null,
	/**  是否为临时线程（不持久化到磁盘）。 */
	ephemeral?: boolean,
	/**  完整协议参数 JSON。 */
	paramsJson?: string | null,
};

/**
 *  `thread/fork` 命令的参数。
 * 
 *  协议层 ThreadForkParams 有 17 个字段，DTO 暴露常用字段 + params_json。
 */
export type ThreadForkArgs_Serialize = {
	/**  要分叉的源线程 ID。 */
	threadId: string,
	/**  分叉点 turn ID（为空时取最后一个 turn）。 */
	lastTurnId?: string | null,
	/**  模型名称。 */
	model?: string | null,
	/**  模型提供商。 */
	modelProvider?: string | null,
	/**  工作目录。 */
	cwd?: string | null,
	/**  是否为临时线程（不持久化到磁盘）。 */
	ephemeral?: boolean,
	/**  完整协议参数 JSON。 */
	paramsJson?: string | null,
};

/**  `thread/goal/clear` 命令的参数。 */
export type ThreadGoalClearArgs = {
	/**  线程 ID。 */
	threadId: string,
};

/**  `thread/goal/get` 命令的参数。 */
export type ThreadGoalGetArgs = {
	/**  线程 ID。 */
	threadId: string,
};

/**  `thread/goal/set` 命令的参数。 */
export type ThreadGoalSetArgs = ThreadGoalSetArgs_Serialize | ThreadGoalSetArgs_Deserialize;

/**  `thread/goal/set` 命令的参数。 */
export type ThreadGoalSetArgs_Deserialize = {
	/**  线程 ID。 */
	threadId: string,
	/**  目标描述。 */
	objective?: string | null,
	/**  目标状态（active/paused/blocked/usageLimited/budgetLimited/complete）。 */
	status?: string | null,
	/**
	 *  Token 预算（null 表示清除）。
	 * 
	 *  注意：使用 `f64` 而非 `i64`，因为 tauri-specta 禁止导出 BigInt 类型
	 * （i64/u64 等）到 TypeScript。serde_json 在反序列化为协议层的 `i64` 时
	 *  会自动转换整数值。
	 */
	tokenBudget?: number | null,
};

/**  `thread/goal/set` 命令的参数。 */
export type ThreadGoalSetArgs_Serialize = {
	/**  线程 ID。 */
	threadId: string,
	/**  目标描述。 */
	objective?: string | null,
	/**  目标状态（active/paused/blocked/usageLimited/budgetLimited/complete）。 */
	status?: string | null,
	/**
	 *  Token 预算（null 表示清除）。
	 * 
	 *  注意：使用 `f64` 而非 `i64`，因为 tauri-specta 禁止导出 BigInt 类型
	 * （i64/u64 等）到 TypeScript。serde_json 在反序列化为协议层的 `i64` 时
	 *  会自动转换整数值。
	 */
	tokenBudget?: number | null,
};

/**  `thread/increment_elicitation` 命令的参数（experimental）。 */
export type ThreadIncrementElicitationArgs = {
	/**  线程 ID。 */
	threadId: string,
};

/**
 *  `thread/inject_items` 命令的参数。
 * 
 *  用于向线程追加原始 Responses API items。
 */
export type ThreadInjectItemsArgs = {
	/**  线程 ID。 */
	threadId: string,
	/**  items 的 JSON 数组字符串（每个元素是 Responses API item 对象）。 */
	itemsJson: string,
};

/**
 *  `thread/items/list` 命令的参数（experimental）。
 * 
 *  **核心命令**：用于分页拉取线程消息项，替代前端 mock。
 */
export type ThreadItemsListArgs = ThreadItemsListArgs_Serialize | ThreadItemsListArgs_Deserialize;

/**
 *  `thread/items/list` 命令的参数（experimental）。
 * 
 *  **核心命令**：用于分页拉取线程消息项，替代前端 mock。
 */
export type ThreadItemsListArgs_Deserialize = {
	/**  线程 ID。 */
	threadId: string,
	/**  按 turn ID 过滤（为空时返回线程内所有 item）。 */
	turnId?: string | null,
	/**  分页游标。 */
	cursor?: string | null,
	/**  每页数量。 */
	limit?: number | null,
	/**  排序方向（asc/desc，默认 asc）。 */
	sortDirection?: string | null,
};

/**
 *  `thread/items/list` 命令的参数（experimental）。
 * 
 *  **核心命令**：用于分页拉取线程消息项，替代前端 mock。
 */
export type ThreadItemsListArgs_Serialize = {
	/**  线程 ID。 */
	threadId: string,
	/**  按 turn ID 过滤（为空时返回线程内所有 item）。 */
	turnId?: string | null,
	/**  分页游标。 */
	cursor?: string | null,
	/**  每页数量。 */
	limit?: number | null,
	/**  排序方向（asc/desc，默认 asc）。 */
	sortDirection?: string | null,
};

/**
 *  `thread/list` 命令的参数。
 * 
 *  对应 codex-rs 的 `v2::ThreadListParams`，简化为桌面端常用字段。
 */
export type ThreadListArgs = ThreadListArgs_Serialize | ThreadListArgs_Deserialize;

/**
 *  `thread/list` 命令的参数。
 * 
 *  对应 codex-rs 的 `v2::ThreadListParams`，简化为桌面端常用字段。
 */
export type ThreadListArgs_Deserialize = {
	/**  分页游标（上一次调用返回的 `nextCursor`）。为空时从第一页开始。 */
	cursor?: string | null,
	/**  每页数量。为空时使用服务器默认值（通常 20）。 */
	limit?: number | null,
};

/**
 *  `thread/list` 命令的参数。
 * 
 *  对应 codex-rs 的 `v2::ThreadListParams`，简化为桌面端常用字段。
 */
export type ThreadListArgs_Serialize = {
	/**  分页游标（上一次调用返回的 `nextCursor`）。为空时从第一页开始。 */
	cursor?: string | null,
	/**  每页数量。为空时使用服务器默认值（通常 20）。 */
	limit?: number | null,
};

/**  `thread/loaded/list` 命令的参数。 */
export type ThreadLoadedListArgs = ThreadLoadedListArgs_Serialize | ThreadLoadedListArgs_Deserialize;

/**  `thread/loaded/list` 命令的参数。 */
export type ThreadLoadedListArgs_Deserialize = {
	/**  分页游标。 */
	cursor?: string | null,
	/**  每页数量。 */
	limit?: number | null,
};

/**  `thread/loaded/list` 命令的参数。 */
export type ThreadLoadedListArgs_Serialize = {
	/**  分页游标。 */
	cursor?: string | null,
	/**  每页数量。 */
	limit?: number | null,
};

/**  `thread/memoryMode/set` 命令的参数（experimental）。 */
export type ThreadMemoryModeSetArgs = {
	/**  线程 ID。 */
	threadId: string,
	/**  记忆模式（enabled/disabled）。 */
	mode: string,
};

/**
 *  `thread/metadata/update` 命令的参数。
 * 
 *  协议层支持 git_info 等复杂字段，DTO 用 JSON 字符串承载。
 */
export type ThreadMetadataUpdateArgs = ThreadMetadataUpdateArgs_Serialize | ThreadMetadataUpdateArgs_Deserialize;

/**
 *  `thread/metadata/update` 命令的参数。
 * 
 *  协议层支持 git_info 等复杂字段，DTO 用 JSON 字符串承载。
 */
export type ThreadMetadataUpdateArgs_Deserialize = {
	/**  线程 ID。 */
	threadId: string,
	/**
	 *  Git 信息 JSON（对应 ThreadMetadataGitInfoUpdateParams）。
	 *  格式：`{ "sha": "...", "branch": "...", "originUrl": "..." }`，
	 *  每个字段可为 null 表示清除。
	 */
	gitInfoJson?: string | null,
};

/**
 *  `thread/metadata/update` 命令的参数。
 * 
 *  协议层支持 git_info 等复杂字段，DTO 用 JSON 字符串承载。
 */
export type ThreadMetadataUpdateArgs_Serialize = {
	/**  线程 ID。 */
	threadId: string,
	/**
	 *  Git 信息 JSON（对应 ThreadMetadataGitInfoUpdateParams）。
	 *  格式：`{ "sha": "...", "branch": "...", "originUrl": "..." }`，
	 *  每个字段可为 null 表示清除。
	 */
	gitInfoJson?: string | null,
};

/**  `thread/read` 命令的参数。 */
export type ThreadReadArgs = {
	/**  要读取的线程 ID（必填）。 */
	threadId: string,
	/**  是否包含 turn 和 item 历史。默认 false。 */
	includeTurns?: boolean,
};

/**  `thread/realtime/appendAudio` 命令的参数（experimental）。 */
export type ThreadRealtimeAppendAudioArgs = {
	/**  线程 ID。 */
	threadId: string,
	/**
	 *  音频块的 JSON 字符串（对应 ThreadRealtimeAudioChunk）。
	 *  格式：`{ "data": "<base64>", "sampleRate": 24000, "numChannels": 1, ... }`。
	 */
	audioJson: string,
};

/**  `thread/realtime/appendSpeech` 命令的参数（experimental）。 */
export type ThreadRealtimeAppendSpeechArgs = {
	/**  线程 ID。 */
	threadId: string,
	/**  要合成的文本。 */
	text: string,
};

/**  `thread/realtime/appendText` 命令的参数（experimental）。 */
export type ThreadRealtimeAppendTextArgs = ThreadRealtimeAppendTextArgs_Serialize | ThreadRealtimeAppendTextArgs_Deserialize;

/**  `thread/realtime/appendText` 命令的参数（experimental）。 */
export type ThreadRealtimeAppendTextArgs_Deserialize = {
	/**  线程 ID。 */
	threadId: string,
	/**  要追加的文本。 */
	text: string,
	/**  角色（user/developer/assistant，默认 user）。 */
	role?: string | null,
};

/**  `thread/realtime/appendText` 命令的参数（experimental）。 */
export type ThreadRealtimeAppendTextArgs_Serialize = {
	/**  线程 ID。 */
	threadId: string,
	/**  要追加的文本。 */
	text: string,
	/**  角色（user/developer/assistant，默认 user）。 */
	role?: string | null,
};

/**
 *  `thread/realtime/listVoices` 命令的参数（experimental）。
 * 
 *  协议层为空结构体，DTO 也为空（specta 要求至少有占位）。
 */
export type ThreadRealtimeListVoicesArgs = Record<string, never>;

/**
 *  `thread/realtime/start` 命令的参数（experimental）。
 * 
 *  协议层 ThreadRealtimeStartParams 有 13 个字段（含 RealtimeOutputModality 等），
 *  DTO 用 `params_json` 承载完整协议参数。
 */
export type ThreadRealtimeStartArgs = {
	/**  线程 ID。 */
	threadId: string,
	/**
	 *  完整协议参数 JSON（对应 ThreadRealtimeStartParams）。
	 *  必填字段：outputModality（text/audio）。
	 *  可选字段：model/voice/transport/version/prompt/... 等。
	 */
	paramsJson: string,
};

/**  `thread/realtime/stop` 命令的参数（experimental）。 */
export type ThreadRealtimeStopArgs = {
	/**  线程 ID。 */
	threadId: string,
};

/**
 *  `thread/resume` 命令的参数。
 * 
 *  协议层 ThreadResumeParams 有 17 个字段（含 ResponseItem/SandboxMode 等），
 *  DTO 只暴露桌面端常用字段，其余通过 `params_json` 透传。
 */
export type ThreadResumeArgs = ThreadResumeArgs_Serialize | ThreadResumeArgs_Deserialize;

/**
 *  `thread/resume` 命令的参数。
 * 
 *  协议层 ThreadResumeParams 有 17 个字段（含 ResponseItem/SandboxMode 等），
 *  DTO 只暴露桌面端常用字段，其余通过 `params_json` 透传。
 */
export type ThreadResumeArgs_Deserialize = {
	/**  要恢复的线程 ID。 */
	threadId: string,
	/**  模型名称（覆盖线程默认模型）。 */
	model?: string | null,
	/**  模型提供商。 */
	modelProvider?: string | null,
	/**  工作目录。 */
	cwd?: string | null,
	/**  线程文件路径（thread_id 为空时使用）。 */
	path?: string | null,
	/**  完整协议参数 JSON（覆盖上述字段，用于传递复杂字段）。 */
	paramsJson?: string | null,
};

/**
 *  `thread/resume` 命令的参数。
 * 
 *  协议层 ThreadResumeParams 有 17 个字段（含 ResponseItem/SandboxMode 等），
 *  DTO 只暴露桌面端常用字段，其余通过 `params_json` 透传。
 */
export type ThreadResumeArgs_Serialize = {
	/**  要恢复的线程 ID。 */
	threadId: string,
	/**  模型名称（覆盖线程默认模型）。 */
	model?: string | null,
	/**  模型提供商。 */
	modelProvider?: string | null,
	/**  工作目录。 */
	cwd?: string | null,
	/**  线程文件路径（thread_id 为空时使用）。 */
	path?: string | null,
	/**  完整协议参数 JSON（覆盖上述字段，用于传递复杂字段）。 */
	paramsJson?: string | null,
};

/**
 *  `thread/rollback` 命令的参数。
 * 
 *  注意：后端标记为 DEPRECATED，未来可能移除。
 */
export type ThreadRollbackArgs = {
	/**  要回滚的线程 ID。 */
	threadId: string,
	/**  回滚的 turn 数量。 */
	numTurns: number,
};

/**  `thread/search` 命令的参数（experimental）。 */
export type ThreadSearchArgs = ThreadSearchArgs_Serialize | ThreadSearchArgs_Deserialize;

/**  `thread/search` 命令的参数（experimental）。 */
export type ThreadSearchArgs_Deserialize = {
	/**  搜索关键词。 */
	searchTerm: string,
	/**  分页游标。 */
	cursor?: string | null,
	/**  每页数量。 */
	limit?: number | null,
	/**  排序键（createdAt/updatedAt/recencyAt）。 */
	sortKey?: string | null,
	/**  排序方向（asc/desc）。 */
	sortDirection?: string | null,
	/**  源类型过滤（cli/vscode/exec/appServer/subAgent/...）。 */
	sourceKinds?: string[] | null,
	/**  归档状态过滤。 */
	archived?: boolean | null,
};

/**  `thread/search` 命令的参数（experimental）。 */
export type ThreadSearchArgs_Serialize = {
	/**  搜索关键词。 */
	searchTerm: string,
	/**  分页游标。 */
	cursor?: string | null,
	/**  每页数量。 */
	limit?: number | null,
	/**  排序键（createdAt/updatedAt/recencyAt）。 */
	sortKey?: string | null,
	/**  排序方向（asc/desc）。 */
	sortDirection?: string | null,
	/**  源类型过滤（cli/vscode/exec/appServer/subAgent/...）。 */
	sourceKinds?: string[] | null,
	/**  归档状态过滤。 */
	archived?: boolean | null,
};

/**  `thread/name/set` 命令的参数。 */
export type ThreadSetNameArgs = {
	/**  要重命名的线程 ID。 */
	threadId: string,
	/**  新名称。 */
	name: string,
};

/**
 *  `thread/settings/update` 命令的参数（experimental）。
 * 
 *  协议层 ThreadSettingsUpdateParams 有 13 个字段（含 AskForApproval/SandboxPolicy 等），
 *  DTO 用 `params_json` 承载完整协议参数。
 */
export type ThreadSettingsUpdateArgs = {
	/**  线程 ID。 */
	threadId: string,
	/**
	 *  完整协议参数 JSON（对应 ThreadSettingsUpdateParams）。
	 *  支持字段：cwd/approvalPolicy/approvalsReviewer/sandboxPolicy/permissions/
	 *  model/serviceTier/effort/summary/collaborationMode/personality 等。
	 */
	paramsJson: string,
};

/**  `thread/shellCommand` 命令的参数。 */
export type ThreadShellCommandArgs = {
	/**  线程 ID。 */
	threadId: string,
	/**  要执行的 shell 命令。 */
	command: string,
};

/**
 *  `thread/start` 命令的参数。
 * 
 *  对应 codex-rs 的 `v2::ThreadStartParams`，但只暴露桌面端常用的字段。
 *  其余字段使用默认值。
 */
export type ThreadStartArgs = ThreadStartArgs_Serialize | ThreadStartArgs_Deserialize;

/**
 *  `thread/start` 命令的参数。
 * 
 *  对应 codex-rs 的 `v2::ThreadStartParams`，但只暴露桌面端常用的字段。
 *  其余字段使用默认值。
 */
export type ThreadStartArgs_Deserialize = {
	/**  模型名称（如 `"gpt-4o"`）。为空时使用配置文件中的默认模型。 */
	model?: string | null,
	/**  模型提供商名称。为空时使用默认提供商。 */
	modelProvider?: string | null,
	/**  工作目录路径。为空时使用用户主目录。 */
	cwd?: string | null,
};

/**
 *  `thread/start` 命令的参数。
 * 
 *  对应 codex-rs 的 `v2::ThreadStartParams`，但只暴露桌面端常用的字段。
 *  其余字段使用默认值。
 */
export type ThreadStartArgs_Serialize = {
	/**  模型名称（如 `"gpt-4o"`）。为空时使用配置文件中的默认模型。 */
	model?: string | null,
	/**  模型提供商名称。为空时使用默认提供商。 */
	modelProvider?: string | null,
	/**  工作目录路径。为空时使用用户主目录。 */
	cwd?: string | null,
};

/**  `thread/turns/list` 命令的参数（experimental）。 */
export type ThreadTurnsListArgs = ThreadTurnsListArgs_Serialize | ThreadTurnsListArgs_Deserialize;

/**  `thread/turns/list` 命令的参数（experimental）。 */
export type ThreadTurnsListArgs_Deserialize = {
	/**  线程 ID。 */
	threadId: string,
	/**  分页游标。 */
	cursor?: string | null,
	/**  每页数量。 */
	limit?: number | null,
	/**  排序方向（asc/desc）。 */
	sortDirection?: string | null,
	/**  item 详情级别（notLoaded/summary/full）。 */
	itemsView?: string | null,
};

/**  `thread/turns/list` 命令的参数（experimental）。 */
export type ThreadTurnsListArgs_Serialize = {
	/**  线程 ID。 */
	threadId: string,
	/**  分页游标。 */
	cursor?: string | null,
	/**  每页数量。 */
	limit?: number | null,
	/**  排序方向（asc/desc）。 */
	sortDirection?: string | null,
	/**  item 详情级别（notLoaded/summary/full）。 */
	itemsView?: string | null,
};

/**  `thread/unarchive` 命令的参数。 */
export type ThreadUnarchiveArgs = {
	/**  要取消归档的线程 ID。 */
	threadId: string,
};

/**  `thread/unsubscribe` 命令的参数。 */
export type ThreadUnsubscribeArgs = {
	/**  要取消订阅的线程 ID（必填）。 */
	threadId: string,
};

/**  托盘图标状态 — 控制显示哪个图标。 */
export type TrayIconState = 
/**  默认应用图标 */
"Normal" | 
/**  带通知徽标的图标（如未读消息提示） */
"Notification";

/**  托盘窗口定位 — 控制窗口相对于托盘图标的出现位置。 */
export type TrayPosition = 
/**  托盘图标左上角 */
"TopLeft" | 
/**  托盘图标右上角 */
"TopRight" | 
/**  托盘图标左下角 */
"BottomLeft" | 
/**  托盘图标右下角 */
"BottomRight";

/**
 *  `turn/interrupt` 命令的参数。
 * 
 *  中断指定线程的当前轮次。
 */
export type TurnInterruptArgs = {
	/**  要中断的线程 ID（必填）。 */
	threadId: string,
	/**  要中断的轮次 ID（必填）。 */
	turnId: string,
};

/**
 *  `turn/start` 命令的参数。
 * 
 *  对应 codex-rs 的 `v2::TurnStartParams`，但只暴露桌面端常用的字段。
 *  `input` 为 `Vec<UserInput>` 的 JSON 字符串，由前端序列化后传入，
 *  命令内部用 `serde_json::from_str` 解析为 `serde_json::Value`。
 * 
 *  使用 `String` 而非 `serde_json::Value` 的原因：specta 不支持递归类型
 *  `serde_json::Value`（其 `Number` 变体包含 `i64/u64`，触发 BigInt 禁令）。
 */
export type TurnStartArgs = TurnStartArgs_Serialize | TurnStartArgs_Deserialize;

/**
 *  `turn/start` 命令的参数。
 * 
 *  对应 codex-rs 的 `v2::TurnStartParams`，但只暴露桌面端常用的字段。
 *  `input` 为 `Vec<UserInput>` 的 JSON 字符串，由前端序列化后传入，
 *  命令内部用 `serde_json::from_str` 解析为 `serde_json::Value`。
 * 
 *  使用 `String` 而非 `serde_json::Value` 的原因：specta 不支持递归类型
 *  `serde_json::Value`（其 `Number` 变体包含 `i64/u64`，触发 BigInt 禁令）。
 */
export type TurnStartArgs_Deserialize = {
	/**  要启动轮次的线程 ID（必填）。 */
	threadId: string,
	/**  用户输入内容，是 `Vec<UserInput>` 的 JSON 字符串（前端 `JSON.stringify` 后传入）。 */
	input: string,
	/**  覆盖本轮使用的模型名称。为空时使用线程默认模型。 */
	model?: string | null,
	/**  覆盖本轮的工作目录。为空时使用线程默认工作目录。 */
	cwd?: string | null,
};

/**
 *  `turn/start` 命令的参数。
 * 
 *  对应 codex-rs 的 `v2::TurnStartParams`，但只暴露桌面端常用的字段。
 *  `input` 为 `Vec<UserInput>` 的 JSON 字符串，由前端序列化后传入，
 *  命令内部用 `serde_json::from_str` 解析为 `serde_json::Value`。
 * 
 *  使用 `String` 而非 `serde_json::Value` 的原因：specta 不支持递归类型
 *  `serde_json::Value`（其 `Number` 变体包含 `i64/u64`，触发 BigInt 禁令）。
 */
export type TurnStartArgs_Serialize = {
	/**  要启动轮次的线程 ID（必填）。 */
	threadId: string,
	/**  用户输入内容，是 `Vec<UserInput>` 的 JSON 字符串（前端 `JSON.stringify` 后传入）。 */
	input: string,
	/**  覆盖本轮使用的模型名称。为空时使用线程默认模型。 */
	model?: string | null,
	/**  覆盖本轮的工作目录。为空时使用线程默认工作目录。 */
	cwd?: string | null,
};

/**
 *  `turn/steer` 命令的参数。
 * 
 *  在当前轮次进行中追加用户输入（转向），需要指定当前活跃的 turn ID
 *  作为前置条件，如果不匹配则请求失败。
 * 
 *  `input` 同 `TurnStartArgs.input`，为 JSON 字符串。
 */
export type TurnSteerArgs = {
	/**  要转向的线程 ID（必填）。 */
	threadId: string,
	/**  用户输入内容，是 `Vec<UserInput>` 的 JSON 字符串（前端 `JSON.stringify` 后传入）。 */
	input: string,
	/**  预期的当前活跃 turn ID（必填）。不匹配时请求失败。 */
	expectedTurnId: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

