allowBuilds:
  '@google/genai': set this to true or false
  es5-ext: set this to true or false
  esbuild: set this to true or false
  mongodb-memory-server: set this to true or false
  node-llama-cpp: set this to true or false
  openclaw: set this to true or false
  protobufjs: set this to true or false
  tree-sitter-bash: set this to true or false
