// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls whether the model receives multi-agent delegation instructions and,
 * when it does, whether it should only spawn sub-agents after an explicit user
 * request or may delegate proactively when doing so would help. `none` leaves
 * the multi-agent tools available without injecting delegation instructions.
 */
export type MultiAgentMode = "none" | "explicitRequestOnly" | "proactive";
