blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/zlh12331/Tauri-Desktop-Software-Template/discussions
    about: Ask questions and discuss ideas in Discussions
