// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConsumeAccountRateLimitResetCreditParams = {
/**
 * Identifies one logical reset attempt. A UUID is recommended; reuse the same value when
 * retrying that attempt.
 */
idempotencyKey: string, };
